language: perl
perl:
  - "5.10"

before_install: 
  - "cpanm --quiet --notest Digest::MD5"
  - "cpanm --quiet --notest PerlIO::gzip"
  - "cpanm --quiet --notest XML::Simple"
  - "cpanm --quiet --notest PDL"
  - sudo apt-get update -qq
  - sudo apt-get install -y dos2unix

before_script:
  - echo 'our $VERSION="'`perl ./version.pl`'"' > VERSION
  - perl -MExtUtils::Manifest=mkmanifest -e 'mkmanifest()'



